name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    strategy:
      matrix:
        include:
          - container:
              image: node:20
              credentials:
                username: ${{ vars.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_API_KEY }}
            condition: ${{ vars.DOCKER_HUB_USERNAME && secrets.DOCKER_HUB_API_KEY }}
          - container:
              image: node:20
            condition: ${{ !vars.DOCKER_HUB_USERNAME || !secrets.DOCKER_HUB_API_KEY }}
    runs-on: buildjet-4vcpu-ubuntu-2204
    if: ${{ matrix.condition }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install packages
        run: pnpm install
      - name: Run Lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
