name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    head:
      repo:
        fork: false
jobs:
  lint:
    runs-on: buildjet-4vcpu-ubuntu-2204
    if: github.event.pull_request.head.repo.fork == false
    container:
      image: node:20
      credentials:
        username: ${{ vars.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install packages
        run: pnpm install
      - name: Run Lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
