name: Lint
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: node:20
      credentials:
        username: ${{ github.event.pull_request.head.repo.fork == false && vars.DOCKER_HUB_USERNAME || null }}
        password: ${{ github.event.pull_request.head.repo.fork == false && secrets.DOCKER_HUB_API_KEY || null }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: pnpm setup
        uses: pnpm/action-setup@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          
      - name: Install packages
        run: pnpm install
        
      - name: Run Lint
        run: pnpm lint
        env:
          SKIP_ENV_VALIDATION: true
