name: PR Title Check (forks)
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  pr-title-check:
    runs-on: buildjet-4vcpu-ubuntu-2204
    if: github.event.pull_request.head.repo.fork == true
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run PR title check
        run: |
          node .github/scripts/pr-title-check.js
