name: Tests
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  tests:
    if: github.event.pull_request.head.repo.fork == false || github.event_name == 'push'
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: node:20
      credentials:
        username: "${{ vars.DOCKER_HUB_USERNAME }}"
        password: "${{ secrets.DOCKER_HUB_API_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
      - name: Install packages
        run: pnpm install
      - name: Run Tests
        run: pnpm test
        env:
          SKIP_ENV_VALIDATION: true

  tests-forks:
    if: github.event.pull_request.head.repo.fork == true
    runs-on: buildjet-4vcpu-ubuntu-2204
    container:
      image: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pnpm setup
        uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3
      - name: Install packages
        run: pnpm install
      - name: Run Tests
        run: pnpm test
        env:
          SKIP_ENV_VALIDATION: true
